name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scikit-learn
  - xeus-r
  - r-base
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-purrr
  - r-tibble
  - r-stringr
  - r-forcats
  - r-coursekata
  - r-neuralnet
